name: yearly_planning
description: Show a yearly planner with given dates.
version: 1.0.0
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.hyruledev.yearly_planning
        pluginClass: YearlyPlanningPlugin
      ios:
        pluginClass: YearlyPlanningPlugin
      linux:
        pluginClass: YearlyPlanningPlugin
      macos:
        pluginClass: YearlyPlanningPlugin
      windows:
        pluginClass: YearlyPlanningPluginCApi
      